version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DB_USER: ${USER}
      DB_PASSWORD: ${PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${HOST}
      DB_PORT: ${PORT}
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${PORT}:${PORT}"
